class Actions:
    """Closed catalog of audit action identifiers (spec D3). resource.action[.qualifier]."""

    # auth
    AUTH_LOGIN_SUCCESS = "auth.login.success"
    AUTH_LOGIN_FAILED = "auth.login.failed"
    AUTH_LOGIN_THROTTLED = "auth.login.throttled"
    AUTH_LOGOUT = "auth.logout"
    AUTH_LOGOUT_ALL = "auth.logout_all"
    AUTH_SESSION_REVOKED = "auth.session.revoked"
    AUTH_SESSION_REUSE_DETECTED = "auth.session.reuse_detected"
    AUTH_PASSWORD_CHANGED = "auth.password.changed"
    # accounts
    ACCOUNT_CREATED = "account.created"
    ACCOUNT_UPDATED = "account.updated"
    ACCOUNT_ARCHIVED = "account.archived"
    ACCOUNT_DELETED = "account.deleted"
    ACCOUNT_BALANCE_RECONCILED = "account.balance_reconciled"
    # transactions
    TRANSACTION_CREATED = "transaction.created"
    TRANSACTION_UPDATED = "transaction.updated"
    TRANSACTION_DELETED = "transaction.deleted"
    TRANSACTION_RESTORED = "transaction.restored"
    TRANSACTION_IMPORTED = "transaction.imported"
    # transfers
    TRANSFER_CREATED = "transfer.created"
    TRANSFER_UPDATED = "transfer.updated"
    TRANSFER_DELETED = "transfer.deleted"
    # projects
    PROJECT_CREATED = "project.created"
    PROJECT_UPDATED = "project.updated"
    PROJECT_DELETED = "project.deleted"
    PROJECT_ITEM_CREATED = "project_item.created"
    PROJECT_ITEM_UPDATED = "project_item.updated"
    # assets
    ASSET_CREATED = "asset.created"
    ASSET_UPDATED = "asset.updated"
    ASSET_DELETED = "asset.deleted"
    ASSET_VALUATION_CREATED = "asset.valuation.created"
    ASSET_VALUATION_UPDATED = "asset.valuation.updated"
    # portfolios (investment holdings)
    PORTFOLIO_CREATED = "portfolio.created"
    PORTFOLIO_UPDATED = "portfolio.updated"
    PORTFOLIO_DELETED = "portfolio.deleted"
    HOLDING_CREATED = "holding.created"
    HOLDING_UPDATED = "holding.updated"
    HOLDING_DELETED = "holding.deleted"
    HOLDING_PRICE_RECORDED = "holding_price.recorded"
    # loans
    LOAN_CREATED = "loan.created"
    LOAN_UPDATED = "loan.updated"
    LOAN_DELETED = "loan.deleted"
    LOAN_PAYMENT_RECORDED = "loan_payment.recorded"
    LOAN_PAYMENT_UPDATED = "loan_payment.updated"
    LOAN_PAYMENT_DELETED = "loan_payment.deleted"
    # budgets
    BUDGET_CREATED = "budget.created"
    BUDGET_UPDATED = "budget.updated"
    BUDGET_DELETED = "budget.deleted"
    # categories
    CATEGORY_CREATED = "category.created"
    CATEGORY_UPDATED = "category.updated"
    CATEGORY_ARCHIVED = "category.archived"
    # contacts
    CONTACT_CREATED = "contact.created"
    CONTACT_UPDATED = "contact.updated"
    CONTACT_ARCHIVED = "contact.archived"
    # goals (savings goals, v1.4 — progress is derived from a source, not a ledger)
    GOAL_CREATED = "goal.created"
    GOAL_UPDATED = "goal.updated"
    GOAL_DELETED = "goal.deleted"
    # subscriptions (recurring-service registry — a tracker, not an auto-poster)
    SUBSCRIPTION_CREATED = "subscription.created"
    SUBSCRIPTION_UPDATED = "subscription.updated"
    SUBSCRIPTION_DELETED = "subscription.deleted"
    SUBSCRIPTION_RENEWED = "subscription.renewed"
    # scheduled transactions (Planned domain)
    SCHEDULED_TRANSACTION_CREATED = "scheduled_transaction.created"
    SCHEDULED_TRANSACTION_UPDATED = "scheduled_transaction.updated"
    SCHEDULED_TRANSACTION_POSTED = "scheduled_transaction.posted"
    SCHEDULED_TRANSACTION_SKIPPED = "scheduled_transaction.skipped"
    SCHEDULED_TRANSACTION_DELETED = "scheduled_transaction.deleted"
    # config / data
    SETTINGS_UPDATED = "settings.updated"
    USER_CREATED = "user.created"
    USER_UPDATED = "user.updated"
    SETUP_COMPLETED = "setup.completed"
    BACKUP_CREATED = "backup.created"
    BACKUP_RESTORED = "backup.restored"
    DATA_IMPORTED = "data.imported"
    DATA_EXPORTED = "data.exported"
    DATA_DEMO_SEEDED = "data.demo_seeded"
    DATA_DEMO_REMOVED = "data.demo_removed"
